### ISSUE TITLE
It's not work

### ISSUE THREAD

**Issue by livesguan** [chadyred/glpi-ocsinventory-stack-docker#27]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : centos7.7

### Docker informations
Docker compose version :1.25.5
Docker version : 19.03.8

### Problem's description
*Describe your problem here*
http://10.10.12.4/  redirect http://10.10.12.4/install/install.php
http://10.10.12.4:8080/ is Apache2 Debian Default Page

**Comment by chadyred** [comment]
Hello, thanks for your issue:  

`http://10.10.12.4/ redirect http://10.10.12.4/install/install.php` >> Normal at first start of GLPI
`http://10.10.12.4:8080/ is Apache2 Debian Default Page` >> Exist URI but not needed for human.

Explanation :

GLPI use OCS Inventory as a plugin. I think you never have to go directly in OCS inventory (which is install on 8080).

All your computer on your network (or your VM) could have install the client OCS Inventory :

On OCS Inventory Page it explain here https://ocsinventory-ng.org/?page_id=118&lang=en

> 
> From the central management server, you can upload the packets that will be downloaded using 
> HTTP/HTTPS and launched by the agent on the client computer. OCS remote deployment is 
> configurable so that sent packets impact the network’s quality of service as little as possible. OCS  is used as a deployment tool on parks with more than 150 000 machines.

All your computer have to install the client OCS Inventory to send data on port `8080` which is the server of your client. 

Next, GLPI, through the plugin, will be able to speak with OCS Inventory about all the client data receive on url `/ocsreports`. So  GLPI will get all informations of computer on network.

For example, on Linux, MAC or Windows you have to install client (call Agent), downloadable here : 

https://ocsinventory-ng.org/?page_id=1548&lang=en

Install and configure agent to send data to port `8080` on the same network. 

To test it : create a VM with a Windows ISO and configure network as `bridge`, so you will be able to ping the port `8080` of your host machine which run this docker stack OCS.

Then, download and install agent.

I have documented this here but it is a quite slim... 

> GLPI
> 
> Go to http://localhost with the default credentials:
> 
> login - glpi
> 
> pass - glpi
> OCS Inventory Server
> 
> Go to http://localhost:8080 with the default credentials:
> 
> login - admin
> 
> pass - admin
> URI
> 
> On OCS inventory URL are /ocsreports, /download and /snmp, and for all client agent, configuration have to send infor;ation to URI /ocsinventory for send informations.
> 
>         400 error (Bad Request) on the uri /ocsinventory and 400 forbidden on /download on browser is normal : this url is for agent install on all your devices which are clients and send information about their devices.
> ```

**Comment by livesguan** [comment]
It's ok. Thanks very much. Now still "Wait for glpi/plugins exists.."

**Comment by livesguan** [comment]
Thank very much. It's work.
